version: 2.1

# Define the jobs we want to run for this project
jobs:
  frontend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run: 
         command:  |
          cd frontend
          npm install
          npm run build

  backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          command: |
            cd backend
            npm install
            npm run build

  test-frontend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          command: |
            cd frontend
            npm install
            npm run test 
  test-backend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          command: |
            cd backend
            npm install
            npm run test   

  scan-frontend: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run: 
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force            
            npm audit --audit-level=critical
  scan-backend: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run: 
          command: |
            cd frontend
            npm install  
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical   
  deploy-infrastructre:
    docker: 
      - image: amazon/aws-cli         
    steps:
      - checkout
      - run:
          command: |
           aws cloudformation deploy \
           --template-file .circleci/files/backend.yml \
             -stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
           --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
           --tags project=udapeople


workflows:
  myworkflow:
     jobs:
       - frontend         
       - backend  
       - test-frontend: 
          requires: [frontend]
       - test-backend: 
           requires:
             [backend]

       - scan-frontend: 
            requires:
               [frontend]
       - scan-backend: 
            requires:
               [backend] 
       - deploy-infrastructre:
            requires:    
              [backend]                  
