version: 2.1

# Define the jobs we want to run for this project
jobs:
  frontend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run: 
         command:  |
          cd frontend
          npm install
          npm run build

  backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          command: |
            cd frontend
            npm install
            npm run build
workflows:
  myworkflow:
     jobs:
       - frontend         
       - backend  